version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: operational-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=companydata
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  airflow-webserver:
    image: apache/airflow:2.1.0
    container_name: airflow_webserver
    depends_on:
      - postgres
    ports:
      - "8082:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin:admin@postgres/companydata
      - AIRFLOW__CORE__FERNET_KEY=your_fernet_key
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
    command: webserver

volumes:
  postgres_data:
